# File: .azure/pipelines/ci.yaml
# Pipeline for the continuous integration to verify the changeset is good enuf,
# and has no platform specific content included.

# HINT: PR triggers are setup in the branch policies.
#       Learn more https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#pr-triggers
trigger: none

variables:
 vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    steps:
    - template: /.azure/pipelines/build/build-ci.yml
      parameters:
        Pool: $(vmImageName)
