trigger:
- main

variables:
- name: vmImageName
  value: 'windows-latest'
- name: buildTemplate
  value: /.azure/pipelines/build/build-rm.yml
- name: deployTemplate
  value: /.azure/pipelines/deploy/deploy-rm.yml

name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    steps:
    - template: ${{ variables.buildTemplate }}
      parameters:
        Pool: $(vmImageName)

- stage: Dev_Deployment
  displayName: 'Deploy to Dev'
  variables:
  - group: azure-dev
  jobs:
  - template: ${{ variables.deployTemplate }}
    parameters:
      pool: $(vmImageName)
      env: DEV
      connectedServiceName: $(connected-service-name)
      location: $(location)

- stage: QA_Deployment
  displayName: 'Deploy to QA'
  variables:
  - group: azure-qa  
  condition: succeeded()
  dependsOn: Dev_Deployment
  jobs:
  - template: ${{ variables.deployTemplate }}
    parameters:
      pool: $(vmImageName)
      env: QA
      connectedServiceName: $(connected-service-name)
      location: $(location)

- stage: Prod_Deployment
  displayName: 'Deploy to Prod'
  variables:
  - group: azure-prod
  condition: succeeded()
  dependsOn: QA_Deployment
  jobs:
  - template: ${{ variables.deployTemplate }}
    parameters:
      pool: $(vmImageName)
      env: PROD
      connectedServiceName: $(connected-service-name)
      location: $(location)