parameters:
- name: 'pool'
  type: string  
- name: 'env'
  type: string  
- name: 'connectedServiceName'
  type: string  
- name: 'location'
  type: string  

jobs:
- deployment: Deployment
  displayName: "Deploy to ${{ parameters.env }}"
  environment: ${{ parameters.env }}
  pool:
    vmImage: ${{ parameters.pool }}
  strategy:
    runOnce:
      deploy:
        steps:
        - script: | 
            echo pool=${{ parameters.pool }}
            echo env=${{ parameters.env }}
            echo connectedServiceName=${{ parameters.connectedServiceName }}
            echo location=${{ parameters.location }}

        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'ARM Template deployment: Subscription scope | Resource.ResourceGroup.json'
          inputs:
            connectedServiceName: '${{ parameters.connectedServiceName }}'
            deploymentScope: Subscription
            location: ${{ parameters.location }}
            csmFile: '$(Pipeline.Workspace)\drop\Resource.ResourceGroup.json'
            csmParametersFile: '$(Pipeline.Workspace)\drop\Param.ResourceGroup.${{ lower(parameters.env) }}.json'

        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'ARM Template deployment: Subscription scope | Resource.ApiManagement.json'
          inputs:
            connectedServiceName: '${{ parameters.connectedServiceName }}'
            deploymentScope: Subscription
            location: ${{ parameters.location }}
            csmFile: '$(Pipeline.Workspace)\drop\Resource.ApiManagement.json'
            csmParametersFile: '$(Pipeline.Workspace)\drop\Param.ApiManagement.${{ lower(parameters.env) }}.json'        